<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domain" nsURI="http://org.rs.domain" nsPrefix="domain">
  
  <eClassifiers xsi:type="ecore:EClass" name="ArchimateModelItem" eSuperTypes="http://org.rs#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wrappedModel" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="ItemCatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ArchimateModelItem" containment="true"/>
  </eClassifiers>
  
</ecore:EPackage>